# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f20aede8398e2728a6cdedcc5708fafee51a227886c9eb3df4d5540fafbacd539669579fe4de4404152436922755297fea9d8aec5ce87a78f110e70de1b213

test:
  secret_key_base: 3509c91034cde49e7cba2a05876b5a3c03eb43d3a742f76f0f3ea918f7619bf4145ef78b98723363e42663f7ce7c1c709f7ce4706ecf77d60c479596428f710b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
